spring.application.name=Ticket-Raising-Backendd
# PostgreSQL Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/RRaiseTicket
spring.datasource.username=postgres
spring.datasource.password=sql

# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
#To see sql commands in my console
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Server Port 
server.port=8013